import React, { useState } from 'react';

export const PTDPageBuilder: React.FC = () => {
  // Pre-filled with the user's requested copy
  const [config, setConfig] = useState({
    title: "PAY THE DØLLS™ — Shop",
    subtitle: "The house brand. Secure the bag.",
    description: "All profit fuels Verse Capital. We curate the baseline, but the platform is yours. Submit your designs. If we print it, you split it—50% revenue share.",
    closingTagline: "Create without Permission. Profit without Limit.",
    collectionHandle: "all", // Default to 'all' for simplicity, but allow change
  });

  // THE A-LIST:
  // Apparel     (Clothing)
  // Accessories (Totes, Hats)
  // Artifacts   (Objects/Decor)
  // Art         (Prints/Canvas)
  // Aura        (Wellness/Rituals/Vibes)
  const sections = ['Apparel', 'Accessories', 'Artifacts', 'Art', 'Aura'];

  const generateCode = () => {
    return `{% layout 'theme' %}

<!-- 
  PAY THE DØLLS - Custom Shop Page 
  Generated by Liquid Helper
-->

<div class="bg-white min-h-screen text-black">
  <div class="max-w-[1400px] mx-auto py-24 px-6 md:px-12">
    
    <!-- HEADER SECTION -->
    <header class="mb-16 text-center max-w-4xl mx-auto">
      <h1 class="text-4xl md:text-7xl font-bold uppercase tracking-tight mb-6">
        ${config.title}
      </h1>
      <h2 class="text-xl md:text-2xl font-medium uppercase tracking-widest mb-8 border-b border-black pb-4 inline-block">
        ${config.subtitle}
      </h2>
      
      <!-- CATEGORY NAVIGATION (THE BOXES) -->
      <nav class="flex flex-wrap justify-center gap-4 mb-12">
        ${sections.map(section => `
        <a href="#${section.toLowerCase()}" class="px-6 py-3 border border-black uppercase font-bold tracking-widest text-xs hover:bg-black hover:text-white transition-all duration-300">
          ${section}
        </a>`).join('')}
      </nav>

      <div class="w-16 h-px bg-black mx-auto mb-12"></div>

      <p class="text-[#666] text-lg font-light leading-relaxed max-w-2xl mx-auto">
        ${config.description}
      </p>
    </header>

    <!-- 
       AUTO-FLOW LOGIC
       We capture the collection named '${config.collectionHandle}'.
       If you haven't made specific collections, we use 'all' products 
       and filter them by TAGS.
    -->
    {% assign source_collection = collections['${config.collectionHandle}'] %}
    {% if source_collection.products.size == 0 %}
      {% assign source_collection = collections['all'] %}
    {% endif %}

    <!-- 
       SECTIONS LOOP
       This creates the sections based on your tags.
    -->
    <div class="space-y-32">
${sections.map(section => `
      <!-- SECTION: ${section.toUpperCase()} -->
      <section id="${section.toLowerCase()}" class="ptd-section scroll-mt-32">
        <div class="flex items-end justify-between border-b border-black mb-12 pb-4">
           <h3 class="text-5xl font-bold uppercase tracking-tighter">${section}</h3>
           <a href="/collections/${section.toLowerCase()}" class="text-xs font-mono uppercase tracking-widest underline decoration-1 underline-offset-4 hover:bg-black hover:text-white px-2 py-1 transition-colors">
              View All ${section}
           </a>
        </div>
        
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-x-px gap-y-px bg-gray-200 border border-gray-200">
          {% assign count = 0 %}
          
          {% for product in source_collection.products %}
            {% if product.tags contains '${section}' %}
              {% assign count = count | plus: 1 %}
              
              <!-- PRODUCT CARD -->
              <a href="{{ product.url }}" class="group bg-white relative aspect-[3/4] overflow-hidden block hover:z-10">
                 
                 <!-- Image -->
                 <div class="absolute inset-0">
                    <img 
                      src="{{ product.featured_image | img_url: '800x' }}" 
                      alt="{{ product.title }}"
                      class="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                    />
                 </div>

                 <!-- Overlay Info -->
                 <div class="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors duration-300 flex flex-col justify-end p-6">
                    <div class="bg-white text-black p-4 transform translate-y-full group-hover:translate-y-0 transition-transform duration-300 ease-out">
                       <h4 class="font-bold uppercase tracking-tight text-lg">{{ product.title }}</h4>
                       <div class="flex justify-between items-center mt-2 border-t border-gray-100 pt-2">
                          <span class="font-mono text-sm">{{ product.price | money }}</span>
                          <span class="text-[10px] uppercase tracking-widest bg-black text-white px-2 py-1">View</span>
                       </div>
                    </div>
                 </div>
              </a>

            {% endif %}
          {% endfor %}

          <!-- Empty State (Only shows if 0 products found for this tag) -->
          {% if count == 0 %}
            <div class="col-span-full py-12 text-center bg-gray-50 text-gray-500 font-mono text-sm">
              No products found with tag "<strong>${section}</strong>". <br/>
              Go to Shopify Admin > Products and add the tag <strong>${section}</strong> to your items.
            </div>
          {% endif %}
        </div>
      </section>
`).join('')}
    </div>

    <!-- CLOSING TAGLINE -->
    <div class="mt-32 pt-12 border-t border-black text-center">
        <h2 class="text-2xl md:text-4xl font-black uppercase tracking-tighter italic">
            "${config.closingTagline}"
        </h2>
    </div>

  </div>
</div>
`;
  };

  const copyCode = () => {
    navigator.clipboard.writeText(generateCode());
    alert('Code copied! Create a new Page template in Shopify and paste this in.');
  };

  return (
    <div className="flex flex-col lg:flex-row h-[calc(100vh-64px)] overflow-hidden">
      {/* LEFT: Instructions & Configuration */}
      <div className="w-full lg:w-1/3 bg-purple-50 border-r border-purple-100 overflow-y-auto p-6">
        <h2 className="text-xl font-bold mb-4 text-purple-900">4. PTD Shop Page Builder</h2>
        
        {/* The Answer to "How do I Auto Flow?" */}
        <div className="bg-white rounded-lg shadow-sm border border-purple-200 p-5 mb-8">
          <h3 className="font-bold text-purple-700 mb-2 flex items-center">
            <span className="mr-2">⚡</span> How to "Auto Flow" Products
          </h3>
          <p className="text-sm text-gray-700 mb-4 leading-relaxed">
            You asked how to make new products appear automatically. The secret is <strong>TAGS</strong>.
          </p>
          <ol className="list-decimal ml-4 text-sm text-gray-800 space-y-2">
            <li>Go to Shopify Admin &rarr; <strong>Products</strong>.</li>
            <li>Click on a product (e.g., "Neon Tee").</li>
            <li>Look for the <strong>Tags</strong> section on the right.</li>
            <li>Type one of these exact words and press Enter:</li>
          </ol>
          <div className="flex flex-wrap gap-2 mt-3 ml-4">
             {sections.map(s => (
               <span key={s} className="bg-purple-100 text-purple-800 px-2 py-1 rounded text-xs font-mono font-bold border border-purple-300">
                 {s}
               </span>
             ))}
          </div>
          <p className="text-xs text-gray-500 mt-4 italic">
            Note: The code generated here will automatically look for these tags and place the products in the correct section.
          </p>
        </div>

        <h3 className="font-bold text-gray-900 mb-4 border-t border-purple-200 pt-6">The "A-List" Setup</h3>
        
        <div className="space-y-4">
          <div>
            <label className="block text-xs font-bold uppercase text-gray-500 mb-1">Page Title</label>
            <input 
              type="text" 
              value={config.title}
              onChange={(e) => setConfig({...config, title: e.target.value})}
              className="w-full p-2 border border-gray-300 rounded focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>
          
          <div>
            <label className="block text-xs font-bold uppercase text-gray-500 mb-1">Subtitle</label>
            <input 
              type="text" 
              value={config.subtitle}
              onChange={(e) => setConfig({...config, subtitle: e.target.value})}
              className="w-full p-2 border border-gray-300 rounded focus:ring-2 focus:ring-purple-500 outline-none"
            />
          </div>

          <div>
            <label className="block text-xs font-bold uppercase text-gray-500 mb-1">Description</label>
            <textarea 
              value={config.description}
              onChange={(e) => setConfig({...config, description: e.target.value})}
              rows={4}
              className="w-full p-2 border border-gray-300 rounded focus:ring-2 focus:ring-purple-500 outline-none text-sm leading-relaxed"
            />
          </div>

          <div>
            <label className="block text-xs font-bold uppercase text-gray-500 mb-1">Closing Tagline</label>
            <input 
              type="text" 
              value={config.closingTagline}
              onChange={(e) => setConfig({...config, closingTagline: e.target.value})}
              className="w-full p-2 border border-gray-300 rounded focus:ring-2 focus:ring-purple-500 outline-none italic font-serif"
            />
          </div>
        </div>
      </div>

      {/* CENTER: Preview */}
      <div className="w-full lg:w-1/3 bg-white border-r border-gray-200 overflow-y-auto relative">
         <div className="p-4 bg-gray-100 sticky top-0 z-10 text-xs font-bold uppercase tracking-wider text-gray-600 text-center border-b border-gray-200">
          Preview Structure
        </div>
        <div className="p-8">
            <div className="text-center mb-8">
                <h1 className="text-3xl font-bold uppercase mb-2">{config.title}</h1>
                <p className="text-sm font-medium uppercase tracking-widest border-b border-black pb-2 inline-block mb-4">{config.subtitle}</p>
                
                {/* PREVIEW NAV */}
                <div className="flex flex-wrap justify-center gap-2 mb-6">
                    {sections.map(s => (
                        <div key={s} className="px-2 py-1 border border-black text-[10px] font-bold uppercase hover:bg-black hover:text-white cursor-pointer">
                            {s}
                        </div>
                    ))}
                </div>
                <div className="w-8 h-px bg-black mx-auto mb-6"></div>
                <p className="text-gray-500 text-xs leading-relaxed">{config.description}</p>
            </div>

            <div className="space-y-12">
                {sections.map(section => (
                    <div key={section} className="border-t border-black pt-2">
                        <div className="flex justify-between items-end mb-4">
                            <h3 className="text-2xl font-bold uppercase">{section}</h3>
                            <span className="text-[10px] bg-purple-100 text-purple-800 px-1 rounded">Tag: {section}</span>
                        </div>
                        <div className="grid grid-cols-2 gap-2">
                            <div className="aspect-[3/4] bg-gray-100 flex items-center justify-center text-xs text-gray-400 text-center p-2">
                               Product tagged "{section}"
                            </div>
                            <div className="aspect-[3/4] bg-gray-100 flex items-center justify-center text-xs text-gray-400 text-center p-2">
                               Product tagged "{section}"
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            <div className="mt-12 pt-8 border-t border-black text-center">
                 <h3 className="text-xl font-black uppercase italic opacity-50">"{config.closingTagline}"</h3>
            </div>
        </div>
      </div>

      {/* RIGHT: Code */}
      <div className="w-full lg:w-1/3 bg-[#1e1e1e] overflow-y-auto text-gray-300 flex flex-col">
        <div className="p-4 bg-[#2d2d2d] sticky top-0 z-10 flex justify-between items-center border-b border-[#333]">
          <div>
            <span className="text-xs font-bold uppercase tracking-wider text-purple-400">Generated Liquid</span>
            <p className="text-[10px] text-gray-400">Includes Nav & Anchors</p>
          </div>
          <button 
            onClick={copyCode}
            className="px-6 py-3 bg-purple-600 hover:bg-purple-700 text-white text-sm font-bold rounded transition-colors shadow-lg flex items-center gap-2"
          >
            <span>COPY CODE</span>
          </button>
        </div>
        <div className="p-6 font-mono text-xs leading-relaxed whitespace-pre-wrap select-all">
          {generateCode()}
        </div>
      </div>
    </div>
  );
};
